// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package user

import (
	"database/sql"

	"github.com/shopspring/decimal"
)

type Discount struct {
	DiscountID      int32           `json:"discount_id"`
	OrderID         int32           `json:"order_id"`
	DiscountPercent decimal.Decimal `json:"discount_percent"`
	Description     sql.NullString  `json:"description"`
}

type Order struct {
	OrderID  int32           `json:"order_id"`
	UserID   int32           `json:"user_id"`
	Item     string          `json:"item"`
	Quantity int32           `json:"quantity"`
	Price    decimal.Decimal `json:"price"`
}

type User struct {
	UserID   int32          `json:"user_id"`
	Name     string         `json:"name"`
	Email    string         `json:"email"`
	Location sql.NullString `json:"location"`
}
