// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package user

import (
	"context"

	"github.com/shopspring/decimal"
)

const getOrdersByUserID = `-- name: GetOrdersByUserID :many
SELECT o.order_id, o.user_id, o.item, o.quantity, o.price,
       COALESCE(SUM(d.discount_percent), 0) as discount_percent
FROM orders o
LEFT JOIN discounts d ON o.order_id = d.order_id
WHERE o.user_id = ?
GROUP BY o.order_id, o.user_id, o.item, o.quantity, o.price
ORDER BY o.order_id
LIMIT ? OFFSET ?
`

type GetOrdersByUserIDParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetOrdersByUserIDRow struct {
	OrderID         int32           `json:"order_id"`
	UserID          int32           `json:"user_id"`
	Item            string          `json:"item"`
	Quantity        int32           `json:"quantity"`
	Price           decimal.Decimal `json:"price"`
	DiscountPercent interface{}     `json:"discount_percent"`
}

func (q *Queries) GetOrdersByUserID(ctx context.Context, arg GetOrdersByUserIDParams) ([]GetOrdersByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrdersByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersByUserIDRow
	for rows.Next() {
		var i GetOrdersByUserIDRow
		if err := rows.Scan(
			&i.OrderID,
			&i.UserID,
			&i.Item,
			&i.Quantity,
			&i.Price,
			&i.DiscountPercent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, name, email, location FROM users
WHERE user_id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, userID int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.Location,
	)
	return i, err
}
